name: CQBot
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: 开始
      run: |
            sudo pip install nb-cli
            sudo pip install nonebot-adapter-cqhttp
            cd /home
            git clone https://github.com/yi985432/CQBot
            cd CQBot
            unzip cq-bot.zip
            unzip plugins.zip
            unzip plugins2.zip
            cd cq-bot
            sudo ./go-cqhttp_amd64 &
            cd mybot
            mv /home/plugins/* ./mybot/plugins
            mv /home/plugins2/* ./mybot/plugins
            chmod 0755 ./mybot/plugins/*
            python3 bot.py
