name: CQBot
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: 开始
      run: |
            sudo su
            pip install nb-cli
            pip install nonebot-adapter-cqhttp
            sudo chmod 0777 /home
            cd /home
            git clone https://github.com/yi985432/CQBot
            cd CQBot
            unzip cq-bot.zip
            unzip Plugins.zip
            unzip Plugins2.zip
            mv ./Plugins/* cq-bot/mybot/mybot/plugins
            mv ./Plugins2/* cq-bot/mybot/mybot/plugins
            chmod 0755 cq-bot/mybot/mybot/plugins/*
            cd cq-bot
            ./go-cqhttp_amd64 &
            cd mybot
            python3 bot.py
