name: CQBot
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: 开始
      run: |
            sudo su
            pip install nb-cli
            pip install nonebot-adapter-cqhttp
            sudo chmod 0777 /home
            cd /home
            git clone https://github.com/yi985432/CQBot
            cd CQBot
            unzip cq-bot.zip
            unzip Plugins.zip
            unzip Plugins2.zip
            cd cq-bot
            ./go-cqhttp_amd64 &
            cd mybot
            mv /home/CQBbot/Plugins/* ./mybot/plugins
            mv /home/CQBot/Plugins2/* ./mybot/plugins
            sudo chmod 0755 ./mybot/plugins/*
            python3 bot.py
